### ISSUE TITLE
Code issue

### ISSUE THREAD

**Issue by QienJane** [xkazm/ASFA#1]
Hello!
         I am very sorry to disturb you! You mentioned in the README.md file that the datasets are downloaded via MOABB: "Please manually download the datasets BNCI2014001, BNCI2014002, BNCI2014004 by MOABB.". 
         However, in your ASFA.py, line 257 reads "datasets = ['BNCI2014012', 'BNCI2014014', 'BNCI201402', 'BNCI201501-2', 'BNCI2014014-A', 'BNCI2014014-B']". 
         The names of these two data sets do not correspond to each other, can you tell me how to solve this problem?**

**Comment by Ashone-ww233** [comment]
Hi, I also found this problem when I was using the dataset, how did you solve it, I look forward to receiving your reply.

**Comment by w9595** [comment]
> 

你好,请问你解决这个问题了吗

**Comment by QienJane** [comment]
Hello, I'm just now paying attention to the comments. My problem has been solved.
