### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by QienJane** [xkazm/ASFA#2]
Dear Author,

I recently read your paper and tried to reproduce your results using the MI 2 dataset's left/right hand 2-classification and left/right hand, foot, and tongue 4-classification train data for training and testing. However, I found that when using the 2-classification train data, the ASFA algorithm's accuracy results were only 72.99%-73.84%, which is about 2% lower than the 74.18%-75.06% reported in your paper. The same situation also occurred with the 4-classification train data, where my accuracy results were 54.01%-55.25%, while your reported accuracy results in the paper were 56.92%-57.78%.

I wanted to ask if this difference is within your expectations or if there could be any issues with your code or parameter settings. If possible, could you provide some assistance to help me better understand these results and try to address this issue?

Thank you for writing this paper and providing the source code on Github. I look forward to hearing back from you.

Thank you!

**Comment by xkazm** [comment]
Thank you for your continued interest in our work. The difference may occur with different data-preprocessing procedure, like time duration, and so on. May I ask the results of EA or RA reproduced by you are consistent with my paper?

**Comment by DiRenJieyihao** [comment]
> Dear Author,
> 
> I recently read your paper and tried to reproduce your results using the MI 2 dataset's left/right hand 2-classification and left/right hand, foot, and tongue 4-classification train data for training and testing. However, I found that when using the 2-classification train data, the ASFA algorithm's accuracy results were only 72.99%-73.84%, which is about 2% lower than the 74.18%-75.06% reported in your paper. The same situation also occurred with the 4-classification train data, where my accuracy results were 54.01%-55.25%, while your reported accuracy results in the paper were 56.92%-57.78%.
> 
> I wanted to ask if this difference is within your expectations or if there could be any issues with your code or parameter settings. If possible, could you provide some assistance to help me better understand these results and try to address this issue?
> 
> Thank you for writing this paper and providing the source code on Github. I look forward to hearing back from you.
> 
> Thank you!

你好，我是隔壁广工的，也在做MI。请问下你在跑这份代码的时候，单个subject的结果会跟其他方法的相差很大吗？我跑出来的结果，平均准确率有出入，但是单个subject上跟其他方法相差更大。

**Comment by isZhanqianqian** [comment]
您好！我刚看到您的邮件，在四分类的训练集上的效果会和论文中的有差距，和论文差2%左右，但是选择四分类中2个想象的分类准确率是和论文一样的，请问您那边是如何跑通代码了呀？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月10日(星期一) 下午3:59
收件人: ***@***.***&gt;; 
抄送: "广州大学 詹倩倩 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xkazm/ASFA] Accuracy (Issue #2)





  
Dear Author,
 
I recently read your paper and tried to reproduce your results using the MI 2 dataset's left/right hand 2-classification and left/right hand, foot, and tongue 4-classification train data for training and testing. However, I found that when using the 2-classification train data, the ASFA algorithm's accuracy results were only 72.99%-73.84%, which is about 2% lower than the 74.18%-75.06% reported in your paper. The same situation also occurred with the 4-classification train data, where my accuracy results were 54.01%-55.25%, while your reported accuracy results in the paper were 56.92%-57.78%.
 
I wanted to ask if this difference is within your expectations or if there could be any issues with your code or parameter settings. If possible, could you provide some assistance to help me better understand these results and try to address this issue?
 
Thank you for writing this paper and providing the source code on Github. I look forward to hearing back from you.
 
Thank you!
  
你好，我是隔壁广工的，也在做MI。请问下你在跑这份代码的时候，单个subject的结果会跟其他方法的相差很大吗？我跑出来的结果，平均准确率有出入，但是单个subject上跟其他方法相差更大。
